import type { RawFormFieldDefinition } from '../../types/comparison.types';

// Auto-specific fields
export const autoSpecificFields: RawFormFieldDefinition[] = [
  // Votre projet
  {
    name: 'vehicleType',
    type: 'radio',
    required: true,
    label: 'Type de véhicule',
    subsection: {
      id: 'project_type',
      label: 'Votre projet',
    },
    options: [
      { value: 'current', label: 'Votre véhicule actuel' },
      { value: 'future_purchase', label: 'Un véhicule que vous comptez acheter' },
    ],
  },
  {
    name: 'cardHolder',
    type: 'select',
    required: true,
    label: 'Titulaire de la carte grise',
    subsection: {
      id: 'project_type',
      label: 'Votre projet',
    },
    options: [
      { value: 'me', label: 'Moi (conducteur principal)' },
      { value: 'spouse', label: 'Mon conjoint ou concubin' },
      { value: 'both', label: 'Moi et mon conjoint ou concubin' },
      { value: 'parent', label: 'Votre père ou votre mère' },
      { value: 'other', label: 'Autre titulaire' },
    ],
  },
  {
    name: 'hasSecondaryDriver',
    type: 'select',
    required: true,
    label: 'Conducteur secondaire',
    subsection: {
      id: 'project_type',
      label: 'Votre projet',
    },
    options: [
      { value: 'spouse', label: 'Oui, mon conjoint ou concubin' },
      { value: 'parent', label: 'Oui, mon père ou ma mère' },
      { value: 'child', label: 'Oui, mon enfant' },
      { value: 'no', label: 'Non' },
    ],
  },

  // Votre véhicule
  {
    name: 'make',
    type: 'text',
    required: true,
    label: 'Marque du véhicule',
    subsection: {
      id: 'vehicle_identification',
      label: 'Identification du véhicule',
    },
    validation: { minLength: 2, maxLength: 50 },
    placeholder: 'Marque du véhicule',
  },
  {
    name: 'model',
    type: 'text',
    required: true,
    label: 'Modèle du véhicule',
    subsection: {
      id: 'vehicle_identification',
      label: 'Identification du véhicule',
    },
    validation: { minLength: 2, maxLength: 50 },
    placeholder: 'Modèle du véhicule',
  },
  {
    name: 'version',
    type: 'text',
    required: false,
    label: 'Version du véhicule',
    subsection: {
      id: 'vehicle_identification',
      label: 'Identification du véhicule',
    },
    validation: { maxLength: 100 },
    placeholder: 'Version du véhicule',
  },
  {
    name: 'modelYear',
    type: 'date',
    required: true,
    label: 'Année du modèle',
    subsection: {
      id: 'vehicle_identification',
      label: 'Identification du véhicule',
    },
    helperText: "L'année de fabrication du véhicule (ex: 2020)",
    mask: {
      pattern: '9999',
      placeholder: 'AAAA',
      guide: true,
    },
  },
  {
    name: 'fuelType',
    type: 'card',
    required: true,
    label: 'Type de carburant',
    subsection: {
      id: 'vehicle_characteristics',
      label: 'Caractéristiques du véhicule',
    },
    helpText: 'Sélectionnez le type de carburant de votre véhicule',
    example: 'Exemple: Si vous avez une voiture électrique, choisissez "Électrique"',
    tooltip: "Le type de carburant influence le coût de l'assurance",
    options: [
      { value: 'electric', label: 'Électrique', icon: 'MdElectricCar', description: 'Véhicule électrique' },
      { value: 'gasoline', label: 'Essence', icon: 'MdLocalGasStation', description: 'Moteur essence' },
      { value: 'diesel', label: 'Diesel', icon: 'MdLocalGasStation', description: 'Moteur diesel' },
    ],
  },
  {
    name: 'transmission',
    type: 'select',
    required: true,
    label: 'Type de transmission',
    subsection: {
      id: 'vehicle_characteristics',
      label: 'Caractéristiques du véhicule',
    },
    helpText: 'Type de transmission de votre véhicule',
    example: 'Exemple: Si votre voiture a une boîte manuelle, choisissez "Manuelle"',
    tooltip: "La transmission influence les performances et le coût d'assurance",
    options: [
      { value: 'manual', label: 'Manuelle' },
      { value: 'automatic', label: 'Automatique' },
      { value: 'hybrid', label: 'Hybride' },
    ],
  },
  {
    name: 'bodyType',
    type: 'select',
    required: true,
    label: 'Type de carrosserie',
    subsection: {
      id: 'vehicle_characteristics',
      label: 'Caractéristiques du véhicule',
    },
    helpText: 'Type de carrosserie de votre véhicule',
    example: 'Exemple: Si vous avez une berline, choisissez "Berline"',
    tooltip: "Le type de carrosserie influence le risque et la prime d'assurance",
    options: [
      { value: 'sedan', label: 'Berline' },
      { value: 'hatchback', label: 'Break' },
      { value: 'suv', label: 'SUV' },
      { value: 'coupe', label: 'Coupé' },
      { value: 'convertible', label: 'Cabriolet' },
      { value: 'wagon', label: 'Break' },
      { value: 'other', label: 'Autre' },
    ],
  },
  {
    name: 'doorCount',
    type: 'select',
    required: true,
    label: 'Nombre de portes',
    subsection: {
      id: 'vehicle_characteristics',
      label: 'Caractéristiques du véhicule',
    },
    helpText: 'Nombre de portes de votre véhicule',
    example: 'Exemple: Si votre voiture a 5 portes, choisissez "5 portes"',
    tooltip: 'Le nombre de portes influence la classification du véhicule',
    options: [
      { value: '2', label: '2 portes' },
      { value: '3', label: '3 portes' },
      { value: '4', label: '4 portes' },
      { value: '5', label: '5 portes' },
    ],
  },
  {
    name: 'power',
    type: 'number',
    required: true,
    label: 'Puissance (CV)',
    subsection: {
      id: 'vehicle_characteristics',
      label: 'Caractéristiques du véhicule',
    },
    helpText: 'Puissance de votre véhicule en chevaux fiscaux',
    example: 'Exemple: Si votre voiture fait 90 CV, entrez 90',
    tooltip: "La puissance influence directement le coût de l'assurance",
    validation: { min: 1, max: 1000 },
    helperText: 'La puissance en chevaux fiscaux est indiquée sur votre carte grise',
  },
  {
    name: 'firstRegistrationDate',
    type: 'date',
    required: true,
    label: 'Date de première mise en circulation',
    subsection: {
      id: 'vehicle_dates',
      label: 'Dates & financement du véhicule',
    },
    helperText: 'Date de première mise en circulation du véhicule en France',
    mask: {
      pattern: '99/9999',
      placeholder: 'MM/AAAA',
      guide: true,
    },
  },
  {
    name: 'purchaseDate',
    type: 'date',
    required: true,
    label: "Date d'achat",
    subsection: {
      id: 'vehicle_dates',
      label: 'Dates & financement du véhicule',
    },
    helperText: 'Date à laquelle vous avez acheté le véhicule',
    mask: {
      pattern: '99/9999',
      placeholder: 'MM/AAAA',
      guide: true,
    },
  },
  {
    name: 'vehicleFinancing',
    type: 'select',
    required: true,
    label: 'Mode de financement',
    subsection: {
      id: 'vehicle_dates',
      label: 'Dates & financement du véhicule',
    },
    options: [
      { value: 'cash', label: 'Comptant' },
      { value: 'credit', label: 'Crédit' },
      { value: 'leasing', label: 'Leasing' },
      { value: 'gift', label: 'Don' },
    ],
  },
  {
    name: 'usageType',
    type: 'select',
    required: true,
    label: "Type d'usage",
    subsection: {
      id: 'vehicle_usage',
      label: 'Usage du véhicule',
    },
    options: [
      { value: 'private', label: 'Privé' },
      { value: 'private_work', label: 'Privé et trajet travail' },
      { value: 'private_professional', label: 'Privé et professionnel' },
      { value: 'private_tours', label: 'Privé et tournées régulières' },
    ],
  },
  {
    name: 'annualMileage',
    type: 'select',
    required: true,
    label: 'Kilométrage annuel',
    subsection: {
      id: 'vehicle_usage',
      label: 'Usage du véhicule',
    },
    helpText: 'Estimez le nombre de kilomètres que vous parcourez par an',
    example: 'Exemple: Si vous faites 15 000 km par an, choisissez "10000 - 15000"',
    tooltip: "Plus vous roulez, plus le risque d'accident augmente",
    options: [
      { value: 'less_2000', label: 'Moins de 2000' },
      { value: '2000_4000', label: '2000 - 4000' },
      { value: '4000_6000', label: '4000 - 6000' },
      { value: '6000_8000', label: '6000 - 8000' },
      { value: '8000_10000', label: '8000 - 10000' },
      { value: '10000_15000', label: '10000 - 15000' },
      { value: '15000_20000', label: '15000 - 20000' },
      { value: '20000_30000', label: '20000 - 30000' },
      { value: '30000_40000', label: '30000 - 40000' },
      { value: '40000_50000', label: '40000 - 50000' },
      { value: 'more_50000', label: 'Plus de 50000' },
    ],
  },
  {
    name: 'nightParkingType',
    type: 'select',
    required: true,
    label: 'Stationnement nocturne',
    subsection: {
      id: 'parking_info',
      label: 'Stationnement',
    },
    options: [
      { value: 'individual_garage', label: 'Garage individuel fermé' },
      { value: 'collective_garage', label: 'Parking collectif fermé' },
      { value: 'collective_outdoor', label: 'Parking collectif en plein air' },
      { value: 'private_garden', label: 'Jardin clos privé' },
      { value: 'public_road', label: 'Voie publique' },
    ],
  },
  {
    name: 'nightParkingPostalCode',
    type: 'text',
    required: true,
    label: 'Code postal du stationnement nocturne',
    subsection: {
      id: 'parking_info',
      label: 'Stationnement',
    },
    validation: { pattern: '^[0-9]{5}$' },
    placeholder: 'Code postal du lieu de stationnement la nuit',
  },
  {
    name: 'workPostalCode',
    type: 'text',
    required: false,
    label: 'Code postal du lieu de travail',
    subsection: {
      id: 'parking_info',
      label: 'Stationnement',
    },
    showWhen: { field: 'usageType', in: ['private_work', 'private_professional', 'private_tours'] },
    validation: { pattern: '^[0-9]{5}$' },
    placeholder: 'Code postal du lieu de travail',
  },
  {
    name: 'vehicleOwnershipYears',
    type: 'select',
    required: true,
    label: 'Ancienneté du véhicule',
    subsection: {
      id: 'vehicle_dates',
      label: 'Dates & financement du véhicule',
    },
    options: [
      { value: 'less_1', label: "Moins d'1 an" },
      { value: '1', label: '1 an' },
      { value: '2', label: '2 ans' },
      { value: '3', label: '3 ans' },
      { value: '4', label: '4 ans' },
      { value: '5_plus', label: '5 ans ou plus' },
    ],
  },

  // Votre profil
  {
    name: 'gender',
    type: 'select',
    required: true,
    label: 'Genre',
    subsection: {
      id: 'driver_profile',
      label: 'Profil du conducteur',
    },
    helpText: 'Votre genre',
    example: 'Exemple: Si vous êtes un homme, choisissez "Un homme"',
    tooltip: 'Le genre influence les statistiques de risque',
    options: [
      { value: 'male', label: 'Un homme' },
      { value: 'female', label: 'Une femme' },
    ],
  },
  {
    name: 'birthDate',
    type: 'date',
    required: true,
    label: 'Date de naissance',
    subsection: {
      id: 'driver_profile',
      label: 'Profil du conducteur',
    },
    helpText: 'Votre date de naissance',
    example: 'Exemple: Si vous êtes né le 15/03/1990, entrez 15/03/1990',
    tooltip: "L'âge influence le coût de l'assurance",
    mask: {
      pattern: '99/99/9999',
      placeholder: 'JJ/MM/AAAA',
      guide: true,
    },
  },
  {
    name: 'maritalStatus',
    type: 'select',
    required: true,
    label: 'Situation matrimoniale',
    subsection: {
      id: 'driver_profile',
      label: 'Profil du conducteur',
    },
    helpText: 'Votre situation matrimoniale',
    example: 'Exemple: Si vous êtes marié, choisissez "Marié(e)"',
    tooltip: 'La situation familiale peut influencer les tarifs',
    options: [
      { value: 'single', label: 'Célibataire' },
      { value: 'married', label: 'Marié(e)' },
      { value: 'cohabiting', label: 'En concubinage' },
      { value: 'pacs', label: 'Pacsé(e)' },
    ],
  },
  {
    name: 'profession',
    type: 'select',
    required: true,
    label: 'Profession',
    subsection: {
      id: 'driver_profile',
      label: 'Profil du conducteur',
    },
    helpText: 'Votre profession actuelle',
    example: 'Exemple: Si vous êtes salarié cadre, choisissez "Salarié(e) cadre du secteur privé"',
    tooltip: 'La profession influence le profil de risque',
    options: [
      { value: 'student', label: 'Étudiant' },
      { value: 'private_executive', label: 'Salarié(e) cadre du secteur privé' },
      { value: 'private_employee', label: 'Salarié(e) non-cadre du secteur privé' },
      { value: 'public_executive', label: 'Salarié(e) cadre du secteur public' },
      { value: 'public_employee', label: 'Salarié(e) non-cadre du secteur public' },
      { value: 'independent', label: 'Indépendant(e)' },
      { value: 'entrepreneur', label: 'Entrepreneur(e)' },
      { value: 'retired', label: 'Retraité' },
      { value: 'unemployed', label: 'Sans emploi' },
    ],
  },
  {
    name: 'numberOfChildren',
    type: 'select',
    required: true,
    label: "Nombre d'enfants",
    subsection: {
      id: 'family_info',
      label: 'Situation familiale',
    },
    options: [
      { value: '0', label: '0' },
      { value: '1', label: '1' },
      { value: '2', label: '2' },
      { value: '3_plus', label: '3 ou plus' },
    ],
  },
  {
    name: 'childrenBirthYears',
    type: 'object',
    required: false,
    label: 'Années de naissance des enfants',
    subsection: {
      id: 'family_info',
      label: 'Situation familiale',
    },
    showWhen: { field: 'numberOfChildren', in: ['1', '2', '3_plus'] },
    helperText: "Indiquez l'année de naissance de chaque enfant",
    objectSchema: {
      type: 'array',
      itemSchema: {
        type: 'object',
        fields: [
          {
            name: 'year',
            type: 'number',
            required: true,
            validation: { min: 1990, max: 2025 },
          },
        ],
      },
    },
  },
  {
    name: 'residenceType',
    type: 'select',
    required: true,
    label: 'Type de logement',
    subsection: {
      id: 'residence_info',
      label: 'Logement',
    },
    options: [
      { value: 'house', label: 'Une maison' },
      { value: 'apartment', label: 'Un appartement' },
    ],
  },
  {
    name: 'residenceStatus',
    type: 'select',
    required: true,
    label: "Statut d'occupation",
    subsection: {
      id: 'residence_info',
      label: 'Logement',
    },
    options: [
      { value: 'tenant', label: 'Locataire ou colocataire' },
      { value: 'owner', label: 'Propriétaire' },
      { value: 'other', label: 'Autre' },
    ],
  },
  {
    name: 'residenceStability',
    type: 'select',
    required: true,
    label: 'Stabilité du logement',
    subsection: {
      id: 'residence_info',
      label: 'Logement',
    },
    options: [
      { value: 'fixed', label: 'À une adresse fixe' },
      { value: 'various', label: 'À diverses adresses' },
    ],
  },
  {
    name: 'drivingLicenseDate',
    type: 'date',
    required: true,
    label: "Date d'obtention du permis",
    subsection: {
      id: 'license_info',
      label: 'Permis de conduire',
    },
    helperText: "Date d'obtention de votre permis de conduire",
    mask: {
      pattern: '99/99/9999',
      placeholder: 'JJ/MM/AAAA',
      guide: true,
    },
  },
  {
    name: 'licenseType',
    type: 'select',
    required: true,
    label: 'Type de permis',
    subsection: {
      id: 'license_info',
      label: 'Permis de conduire',
    },
    options: [
      { value: 'b', label: 'Permis B' },
      { value: 'b_accompanied', label: 'Permis B avec conduite accompagnée' },
      { value: 'foreign_eu', label: 'Permis étranger obtenu en Union Européenne' },
      { value: 'foreign_non_eu', label: 'Permis étranger obtenu hors Union Européenne' },
    ],
  },
  {
    name: 'licenseSuspension',
    type: 'select',
    required: true,
    label: 'Suspension/annulation du permis',
    subsection: {
      id: 'license_info',
      label: 'Permis de conduire',
    },
    options: [
      { value: 'never', label: 'Non, jamais' },
      { value: 'suspended_less_5', label: 'Oui, suspendu il y a moins de 5 ans' },
      { value: 'cancelled_less_5', label: 'Oui, annulé il y a moins de 5 ans' },
      { value: 'withdrawn_less_5', label: 'Oui, retiré il y a moins de 5 ans' },
      { value: 'suspended_more_5', label: 'Oui, suspendu il y a plus de 5 ans' },
    ],
  },
  {
    name: 'suspensionDuration',
    type: 'select',
    required: false,
    label: 'Durée de la suspension',
    subsection: {
      id: 'license_info',
      label: 'Permis de conduire',
    },
    showWhen: { field: 'licenseSuspension', in: ['suspended_less_5', 'cancelled_less_5', 'withdrawn_less_5'] },
    options: [
      { value: '1_month', label: '1 mois' },
      { value: '2_months', label: '2 mois' },
      { value: '3_months', label: '3 mois' },
      { value: '4_months', label: '4 mois' },
      { value: '5_months', label: '5 mois' },
      { value: '6_months', label: '6 mois' },
      { value: '7_months', label: '7 mois' },
      { value: '8_months', label: '8 mois' },
      { value: '9_months', label: '9 mois' },
      { value: '10_months', label: '10 mois' },
      { value: '11_months', label: '11 mois' },
      { value: '12_months', label: '12 mois' },
      { value: '13_months', label: '13 mois' },
      { value: '14_months', label: '14 mois' },
      { value: '15_months', label: '15 mois' },
      { value: '16_months', label: '16 mois' },
      { value: '17_months', label: '17 mois' },
      { value: '18_months', label: '18 mois' },
      { value: '19_months', label: '19 mois' },
      { value: '20_months', label: '20 mois' },
      { value: '21_months', label: '21 mois' },
      { value: '22_months', label: '22 mois' },
      { value: '23_months', label: '23 mois' },
      { value: '24_months', label: '24 mois' },
      { value: '25_months', label: '25 mois' },
      { value: '26_months', label: '26 mois' },
      { value: '27_months', label: '27 mois' },
      { value: '28_months', label: '28 mois' },
      { value: '29_months', label: '29 mois' },
      { value: '30_months', label: '30 mois' },
      { value: '31_months', label: '31 mois' },
      { value: '32_months', label: '32 mois' },
      { value: '33_months', label: '33 mois' },
      { value: '34_months', label: '34 mois' },
      { value: '35_months', label: '35 mois' },
      { value: '36_months', label: '36 mois' },
    ],
  },
  {
    name: 'spouseHasLicense',
    type: 'select',
    required: false,
    label: 'Conjoint a un permis',
    subsection: {
      id: 'spouse_info',
      label: 'Informations conjoint',
    },
    showWhen: { field: 'maritalStatus', in: ['married', 'cohabiting', 'pacs'] },
    options: [
      { value: 'yes', label: 'Oui' },
      { value: 'no', label: 'Non' },
    ],
  },
  {
    name: 'spouseLicenseDate',
    type: 'date',
    required: false,
    label: "Date d'obtention du permis du conjoint",
    subsection: {
      id: 'spouse_info',
      label: 'Informations conjoint',
    },
    showWhen: { field: 'spouseHasLicense', equals: 'yes' },
    helperText: 'Quand a-t-il/elle eu son permis ?',
    mask: {
      pattern: '99/99/9999',
      placeholder: 'JJ/MM/AAAA',
      guide: true,
    },
  },
  {
    name: 'spouseBirthDate',
    type: 'date',
    required: false,
    label: 'Date de naissance du conjoint',
    subsection: {
      id: 'spouse_info',
      label: 'Informations conjoint',
    },
    showWhen: { field: 'spouseHasLicense', equals: 'yes' },
    helperText: 'Quelle est sa date de naissance ?',
    mask: {
      pattern: '99/99/9999',
      placeholder: 'JJ/MM/AAAA',
      guide: true,
    },
  },
  {
    name: 'spouseIsMainDriver',
    type: 'select',
    required: false,
    label: 'Conjoint conducteur principal',
    subsection: {
      id: 'spouse_info',
      label: 'Informations conjoint',
    },
    showWhen: { field: 'spouseHasLicense', equals: 'yes' },
    options: [
      { value: 'yes', label: 'Oui' },
      { value: 'no', label: 'Non' },
    ],
  },

  // Vos antécédents
  {
    name: 'isCurrentlyInsured',
    type: 'select',
    required: true,
    label: 'Actuellement assuré',
    subsection: {
      id: 'insurance_history',
      label: "Historique d'assurance",
    },
    options: [
      { value: 'main_driver', label: 'Oui, comme conducteur principal' },
      { value: 'secondary_driver', label: 'Oui, comme conducteur secondaire' },
      { value: 'no', label: 'Non' },
    ],
  },
  {
    name: 'yearsInsured',
    type: 'select',
    required: true,
    label: "Années d'assurance",
    subsection: {
      id: 'insurance_history',
      label: "Historique d'assurance",
    },
    helperText: "Depuis combien d'années êtes-vous assuré ?",
    options: [], // Will be populated dynamically by frontend using dayjs
  },
  {
    name: 'bonusMalus',
    type: 'select',
    required: true,
    label: 'Coefficient bonus/malus',
    subsection: {
      id: 'insurance_history',
      label: "Historique d'assurance",
    },
    helpText: 'Indiquez votre coefficient bonus/malus actuel',
    example: 'Exemple: Si vous avez 20% de bonus, choisissez "0,8 soit 20% de bonus"',
    tooltip: 'Le bonus/malus reflète votre historique de conduite et influence le prix',
    options: [
      { value: '50_more_3_years', label: '50% depuis plus de 3 ans' },
      { value: '50_3_years', label: '50% depuis 3 ans' },
      { value: '50_2_years', label: '50% depuis 2 ans' },
      { value: '50_1_year', label: '50% depuis 1 an' },
      { value: '50_less_1_year', label: "50% depuis moins d'un an" },
      { value: '0.51', label: '0,51 soit 49% de bonus' },
      { value: '0.52', label: '0,52 soit 48% de bonus' },
      { value: '0.53', label: '0,53 soit 47% de bonus' },
      { value: '0.54', label: '0,54 soit 46% de bonus' },
      { value: '0.55', label: '0,55 soit 45% de bonus' },
      { value: '0.56', label: '0,56 soit 44% de bonus' },
      { value: '0.57', label: '0,57 soit 43% de bonus' },
      { value: '0.58', label: '0,58 soit 42% de bonus' },
      { value: '0.59', label: '0,59 soit 41% de bonus' },
      { value: '0.6', label: '0,6 soit 40% de bonus' },
      { value: '0.61', label: '0,61 soit 39% de bonus' },
      { value: '0.62', label: '0,62 soit 38% de bonus' },
      { value: '0.63', label: '0,63 soit 37% de bonus' },
      { value: '0.64', label: '0,64 soit 36% de bonus' },
      { value: '0.65', label: '0,65 soit 35% de bonus' },
      { value: '0.66', label: '0,66 soit 34% de bonus' },
      { value: '0.67', label: '0,67 soit 33% de bonus' },
      { value: '0.68', label: '0,68 soit 32% de bonus' },
      { value: '0.69', label: '0,69 soit 31% de bonus' },
      { value: '0.7', label: '0,7 soit 30% de bonus' },
      { value: '0.71', label: '0,71 soit 29% de bonus' },
      { value: '0.72', label: '0,72 soit 28% de bonus' },
      { value: '0.73', label: '0,73 soit 27% de bonus' },
      { value: '0.74', label: '0,74 soit 26% de bonus' },
      { value: '0.75', label: '0,75 soit 25% de bonus' },
      { value: '0.76', label: '0,76 soit 24% de bonus' },
      { value: '0.77', label: '0,77 soit 23% de bonus' },
      { value: '0.78', label: '0,78 soit 22% de bonus' },
      { value: '0.79', label: '0,79 soit 21% de bonus' },
      { value: '0.8', label: '0,8 soit 20% de bonus' },
      { value: '0.81', label: '0,81 soit 19% de bonus' },
      { value: '0.82', label: '0,82 soit 18% de bonus' },
      { value: '0.83', label: '0,83 soit 17% de bonus' },
      { value: '0.84', label: '0,84 soit 16% de bonus' },
      { value: '0.85', label: '0,85 soit 15% de bonus' },
      { value: '0.86', label: '0,86 soit 14% de bonus' },
      { value: '0.87', label: '0,87 soit 13% de bonus' },
      { value: '0.88', label: '0,88 soit 12% de bonus' },
      { value: '0.89', label: '0,89 soit 11% de bonus' },
      { value: '0.9', label: '0,9 soit 10% de bonus' },
      { value: '0.91', label: '0,91 soit 9% de bonus' },
      { value: '0.92', label: '0,92 soit 8% de bonus' },
      { value: '0.93', label: '0,93 soit 7% de bonus' },
      { value: '0.94', label: '0,94 soit 6% de bonus' },
      { value: '0.95', label: '0,95 soit 5% de bonus' },
      { value: '0.96', label: '0,96 soit 4% de bonus' },
      { value: '0.97', label: '0,97 soit 3% de bonus' },
      { value: '0.98', label: '0,98 soit 2% de bonus' },
      { value: '0.99', label: '0,99 soit 1% de bonus' },
      { value: '1', label: '1 soit ni bonus, ni malus' },
      { value: '1.01', label: '1,01 soit 1% de malus' },
      { value: '1.02', label: '1,02 soit 2% de malus' },
      { value: '1.03', label: '1,03 soit 3% de malus' },
      { value: '1.04', label: '1,04 soit 4% de malus' },
      { value: '1.05', label: '1,05 soit 5% de malus' },
      { value: '1.06', label: '1,06 soit 6% de malus' },
      { value: '1.07', label: '1,07 soit 7% de malus' },
      { value: '1.08', label: '1,08 soit 8% de malus' },
      { value: '1.09', label: '1,09 soit 9% de malus' },
      { value: '1.1', label: '1,1 soit 10% de malus' },
      { value: '1.11', label: '1,11 soit 11% de malus' },
      { value: '1.12', label: '1,12 soit 12% de malus' },
      { value: '1.13', label: '1,13 soit 13% de malus' },
      { value: '1.14', label: '1,14 soit 14% de malus' },
      { value: '1.15', label: '1,15 soit 15% de malus' },
      { value: '1.16', label: '1,16 soit 16% de malus' },
      { value: '1.17', label: '1,17 soit 17% de malus' },
      { value: '1.18', label: '1,18 soit 18% de malus' },
      { value: '1.19', label: '1,19 soit 19% de malus' },
      { value: '1.2', label: '1,2 soit 20% de malus' },
      { value: '1.21', label: '1,21 soit 21% de malus' },
      { value: '1.22', label: '1,22 soit 22% de malus' },
      { value: '1.23', label: '1,23 soit 23% de malus' },
      { value: '1.24', label: '1,24 soit 24% de malus' },
      { value: '1.25', label: '1,25 soit 25% de malus' },
      { value: '1.26', label: '1,26 soit 26% de malus' },
      { value: '1.27', label: '1,27 soit 27% de malus' },
      { value: '1.28', label: '1,28 soit 28% de malus' },
      { value: '1.29', label: '1,29 soit 29% de malus' },
      { value: '1.3', label: '1,3 soit 30% de malus' },
      { value: '1.31', label: '1,31 soit 31% de malus' },
      { value: '1.32', label: '1,32 soit 32% de malus' },
      { value: '1.33', label: '1,33 soit 33% de malus' },
      { value: '1.34', label: '1,34 soit 34% de malus' },
      { value: '1.35', label: '1,35 soit 35% de malus' },
      { value: '1.36', label: '1,36 soit 36% de malus' },
      { value: '1.37', label: '1,37 soit 37% de malus' },
      { value: '1.38', label: '1,38 soit 38% de malus' },
      { value: '1.39', label: '1,39 soit 39% de malus' },
      { value: '1.4', label: '1,4 soit 40% de malus' },
      { value: '1.41', label: '1,41 soit 41% de malus' },
      { value: '1.42', label: '1,42 soit 42% de malus' },
      { value: '1.43', label: '1,43 soit 43% de malus' },
      { value: '1.44', label: '1,44 soit 44% de malus' },
      { value: '1.45', label: '1,45 soit 45% de malus' },
      { value: '1.46', label: '1,46 soit 46% de malus' },
      { value: '1.47', label: '1,47 soit 47% de malus' },
      { value: '1.48', label: '1,48 soit 48% de malus' },
      { value: '1.49', label: '1,49 soit 49% de malus' },
      { value: '1.5', label: '1,5 soit 50% de malus' },
      { value: '1.51', label: '1,51 soit 51% de malus' },
      { value: '1.52', label: '1,52 soit 52% de malus' },
      { value: '1.53', label: '1,53 soit 53% de malus' },
      { value: '1.54', label: '1,54 soit 54% de malus' },
      { value: '1.55', label: '1,55 soit 55% de malus' },
      { value: '1.56', label: '1,56 soit 56% de malus' },
      { value: '1.57', label: '1,57 soit 57% de malus' },
      { value: '1.58', label: '1,58 soit 58% de malus' },
      { value: '1.59', label: '1,59 soit 59% de malus' },
      { value: '1.6', label: '1,6 soit 60% de malus' },
      { value: '1.61', label: '1,61 soit 61% de malus' },
      { value: '1.62', label: '1,62 soit 62% de malus' },
      { value: '1.63', label: '1,63 soit 63% de malus' },
      { value: '1.64', label: '1,64 soit 64% de malus' },
      { value: '1.65', label: '1,65 soit 65% de malus' },
      { value: '1.66', label: '1,66 soit 66% de malus' },
      { value: '1.67', label: '1,67 soit 67% de malus' },
      { value: '1.68', label: '1,68 soit 68% de malus' },
      { value: '1.69', label: '1,69 soit 69% de malus' },
      { value: '1.7', label: '1,7 soit 70% de malus' },
      { value: '1.71', label: '1,71 soit 71% de malus' },
      { value: '1.72', label: '1,72 soit 72% de malus' },
      { value: '1.73', label: '1,73 soit 73% de malus' },
      { value: '1.74', label: '1,74 soit 74% de malus' },
      { value: '1.75', label: '1,75 soit 75% de malus' },
      { value: '1.76', label: '1,76 soit 76% de malus' },
      { value: '1.77', label: '1,77 soit 77% de malus' },
      { value: '1.78', label: '1,78 soit 78% de malus' },
      { value: '1.79', label: '1,79 soit 79% de malus' },
      { value: '1.8', label: '1,8 soit 80% de malus' },
      { value: '1.81', label: '1,81 soit 81% de malus' },
      { value: '1.82', label: '1,82 soit 82% de malus' },
      { value: '1.83', label: '1,83 soit 83% de malus' },
      { value: '1.84', label: '1,84 soit 84% de malus' },
      { value: '1.85', label: '1,85 soit 85% de malus' },
      { value: '1.86', label: '1,86 soit 86% de malus' },
      { value: '1.87', label: '1,87 soit 87% de malus' },
      { value: '1.88', label: '1,88 soit 88% de malus' },
      { value: '1.89', label: '1,89 soit 89% de malus' },
      { value: '1.9', label: '1,9 soit 90% de malus' },
      { value: '1.91', label: '1,91 soit 91% de malus' },
      { value: '1.92', label: '1,92 soit 92% de malus' },
      { value: '1.93', label: '1,93 soit 93% de malus' },
      { value: '1.94', label: '1,94 soit 94% de malus' },
      { value: '1.95', label: '1,95 soit 95% de malus' },
      { value: '1.96', label: '1,96 soit 96% de malus' },
      { value: '1.97', label: '1,97 soit 97% de malus' },
      { value: '1.98', label: '1,98 soit 98% de malus' },
      { value: '1.99', label: '1,99 soit 99% de malus' },
      { value: '2', label: '2 soit 100% de malus' },
      { value: '2.01', label: '2,01 soit 101% de malus' },
      { value: '2.02', label: '2,02 soit 102% de malus' },
      { value: '2.03', label: '2,03 soit 103% de malus' },
      { value: '2.04', label: '2,04 soit 104% de malus' },
      { value: '2.05', label: '2,05 soit 105% de malus' },
      { value: '2.06', label: '2,06 soit 106% de malus' },
      { value: '2.07', label: '2,07 soit 107% de malus' },
      { value: '2.08', label: '2,08 soit 108% de malus' },
      { value: '2.09', label: '2,09 soit 109% de malus' },
      { value: '2.1', label: '2,1 soit 110% de malus' },
      { value: '2.11', label: '2,11 soit 111% de malus' },
      { value: '2.12', label: '2,12 soit 112% de malus' },
      { value: '2.13', label: '2,13 soit 113% de malus' },
      { value: '2.14', label: '2,14 soit 114% de malus' },
      { value: '2.15', label: '2,15 soit 115% de malus' },
      { value: '2.16', label: '2,16 soit 116% de malus' },
      { value: '2.17', label: '2,17 soit 117% de malus' },
      { value: '2.18', label: '2,18 soit 118% de malus' },
      { value: '2.19', label: '2,19 soit 119% de malus' },
      { value: '2.2', label: '2,2 soit 120% de malus' },
      { value: '2.21', label: '2,21 soit 121% de malus' },
      { value: '2.22', label: '2,22 soit 122% de malus' },
      { value: '2.23', label: '2,23 soit 123% de malus' },
      { value: '2.24', label: '2,24 soit 124% de malus' },
      { value: '2.25', label: '2,25 soit 125% de malus' },
      { value: '2.26', label: '2,26 soit 126% de malus' },
      { value: '2.27', label: '2,27 soit 127% de malus' },
      { value: '2.28', label: '2,28 soit 128% de malus' },
      { value: '2.29', label: '2,29 soit 129% de malus' },
      { value: '2.3', label: '2,3 soit 130% de malus' },
      { value: '2.31', label: '2,31 soit 131% de malus' },
      { value: '2.32', label: '2,32 soit 132% de malus' },
      { value: '2.33', label: '2,33 soit 133% de malus' },
      { value: '2.34', label: '2,34 soit 134% de malus' },
      { value: '2.35', label: '2,35 soit 135% de malus' },
      { value: '2.36', label: '2,36 soit 136% de malus' },
      { value: '2.37', label: '2,37 soit 137% de malus' },
      { value: '2.38', label: '2,38 soit 138% de malus' },
      { value: '2.39', label: '2,39 soit 139% de malus' },
      { value: '2.4', label: '2,4 soit 140% de malus' },
      { value: '2.41', label: '2,41 soit 141% de malus' },
      { value: '2.42', label: '2,42 soit 142% de malus' },
      { value: '2.43', label: '2,43 soit 143% de malus' },
      { value: '2.44', label: '2,44 soit 144% de malus' },
      { value: '2.45', label: '2,45 soit 145% de malus' },
      { value: '2.46', label: '2,46 soit 146% de malus' },
      { value: '2.47', label: '2,47 soit 147% de malus' },
      { value: '2.48', label: '2,48 soit 148% de malus' },
      { value: '2.49', label: '2,49 soit 149% de malus' },
      { value: '2.5', label: '2,5 soit 150% de malus' },
      { value: '2.51', label: '2,51 soit 151% de malus' },
      { value: '2.52', label: '2,52 soit 152% de malus' },
      { value: '2.53', label: '2,53 soit 153% de malus' },
      { value: '2.54', label: '2,54 soit 154% de malus' },
      { value: '2.55', label: '2,55 soit 155% de malus' },
      { value: '2.56', label: '2,56 soit 156% de malus' },
      { value: '2.57', label: '2,57 soit 157% de malus' },
      { value: '2.58', label: '2,58 soit 158% de malus' },
      { value: '2.59', label: '2,59 soit 159% de malus' },
      { value: '2.6', label: '2,6 soit 160% de malus' },
      { value: '2.61', label: '2,61 soit 161% de malus' },
      { value: '2.62', label: '2,62 soit 162% de malus' },
      { value: '2.63', label: '2,63 soit 163% de malus' },
      { value: '2.64', label: '2,64 soit 164% de malus' },
      { value: '2.65', label: '2,65 soit 165% de malus' },
      { value: '2.66', label: '2,66 soit 166% de malus' },
      { value: '2.67', label: '2,67 soit 167% de malus' },
      { value: '2.68', label: '2,68 soit 168% de malus' },
      { value: '2.69', label: '2,69 soit 169% de malus' },
      { value: '2.7', label: '2,7 soit 170% de malus' },
      { value: '2.71', label: '2,71 soit 171% de malus' },
      { value: '2.72', label: '2,72 soit 172% de malus' },
      { value: '2.73', label: '2,73 soit 173% de malus' },
      { value: '2.74', label: '2,74 soit 174% de malus' },
      { value: '2.75', label: '2,75 soit 175% de malus' },
      { value: '2.76', label: '2,76 soit 176% de malus' },
      { value: '2.77', label: '2,77 soit 177% de malus' },
      { value: '2.78', label: '2,78 soit 178% de malus' },
      { value: '2.79', label: '2,79 soit 179% de malus' },
      { value: '2.8', label: '2,8 soit 180% de malus' },
      { value: '2.81', label: '2,81 soit 181% de malus' },
      { value: '2.82', label: '2,82 soit 182% de malus' },
      { value: '2.83', label: '2,83 soit 183% de malus' },
      { value: '2.84', label: '2,84 soit 184% de malus' },
      { value: '2.85', label: '2,85 soit 185% de malus' },
      { value: '2.86', label: '2,86 soit 186% de malus' },
      { value: '2.87', label: '2,87 soit 187% de malus' },
      { value: '2.88', label: '2,88 soit 188% de malus' },
      { value: '2.89', label: '2,89 soit 189% de malus' },
      { value: '2.9', label: '2,9 soit 190% de malus' },
      { value: '2.91', label: '2,91 soit 191% de malus' },
      { value: '2.92', label: '2,92 soit 192% de malus' },
      { value: '2.93', label: '2,93 soit 193% de malus' },
      { value: '2.94', label: '2,94 soit 194% de malus' },
      { value: '2.95', label: '2,95 soit 195% de malus' },
      { value: '2.96', label: '2,96 soit 196% de malus' },
      { value: '2.97', label: '2,97 soit 197% de malus' },
      { value: '2.98', label: '2,98 soit 198% de malus' },
      { value: '2.99', label: '2,99 soit 199% de malus' },
      { value: '3', label: '3 soit 200% de malus' },
      { value: '3.01', label: '3,01 soit 201% de malus' },
      { value: '3.02', label: '3,02 soit 202% de malus' },
      { value: '3.03', label: '3,03 soit 203% de malus' },
      { value: '3.04', label: '3,04 soit 204% de malus' },
      { value: '3.05', label: '3,05 soit 205% de malus' },
      { value: '3.06', label: '3,06 soit 206% de malus' },
      { value: '3.07', label: '3,07 soit 207% de malus' },
      { value: '3.08', label: '3,08 soit 208% de malus' },
      { value: '3.09', label: '3,09 soit 209% de malus' },
      { value: '3.1', label: '3,1 soit 210% de malus' },
      { value: '3.11', label: '3,11 soit 211% de malus' },
      { value: '3.12', label: '3,12 soit 212% de malus' },
      { value: '3.13', label: '3,13 soit 213% de malus' },
      { value: '3.14', label: '3,14 soit 214% de malus' },
      { value: '3.15', label: '3,15 soit 215% de malus' },
      { value: '3.16', label: '3,16 soit 216% de malus' },
      { value: '3.17', label: '3,17 soit 217% de malus' },
      { value: '3.18', label: '3,18 soit 218% de malus' },
      { value: '3.19', label: '3,19 soit 219% de malus' },
      { value: '3.2', label: '3,2 soit 220% de malus' },
      { value: '3.21', label: '3,21 soit 221% de malus' },
      { value: '3.22', label: '3,22 soit 222% de malus' },
      { value: '3.23', label: '3,23 soit 223% de malus' },
      { value: '3.24', label: '3,24 soit 224% de malus' },
      { value: '3.25', label: '3,25 soit 225% de malus' },
      { value: '3.26', label: '3,26 soit 226% de malus' },
      { value: '3.27', label: '3,27 soit 227% de malus' },
      { value: '3.28', label: '3,28 soit 228% de malus' },
      { value: '3.29', label: '3,29 soit 229% de malus' },
      { value: '3.3', label: '3,3 soit 230% de malus' },
      { value: '3.31', label: '3,31 soit 231% de malus' },
      { value: '3.32', label: '3,32 soit 232% de malus' },
      { value: '3.33', label: '3,33 soit 233% de malus' },
      { value: '3.34', label: '3,34 soit 234% de malus' },
      { value: '3.35', label: '3,35 soit 235% de malus' },
      { value: '3.36', label: '3,36 soit 236% de malus' },
      { value: '3.37', label: '3,37 soit 237% de malus' },
      { value: '3.38', label: '3,38 soit 238% de malus' },
      { value: '3.39', label: '3,39 soit 239% de malus' },
      { value: '3.4', label: '3,4 soit 240% de malus' },
      { value: '3.41', label: '3,41 soit 241% de malus' },
      { value: '3.42', label: '3,42 soit 242% de malus' },
      { value: '3.43', label: '3,43 soit 243% de malus' },
      { value: '3.44', label: '3,44 soit 244% de malus' },
      { value: '3.45', label: '3,45 soit 245% de malus' },
      { value: '3.46', label: '3,46 soit 246% de malus' },
      { value: '3.47', label: '3,47 soit 247% de malus' },
      { value: '3.48', label: '3,48 soit 248% de malus' },
      { value: '3.49', label: '3,49 soit 249% de malus' },
      { value: '3.5', label: '3,5 soit 250% de malus' },
    ],
  },
  {
    name: 'contractSuspended',
    type: 'select',
    required: true,
    label: 'Contrat suspendu',
    subsection: {
      id: 'insurance_history',
      label: "Historique d'assurance",
    },
    options: [
      { value: 'no', label: 'Non' },
      { value: 'yes', label: 'Oui' },
    ],
  },
  {
    name: 'isMainDriverOtherVehicle',
    type: 'select',
    required: true,
    label: "Conducteur principal d'un autre véhicule",
    subsection: {
      id: 'insurance_history',
      label: "Historique d'assurance",
    },
    options: [
      { value: 'yes', label: 'Oui' },
      { value: 'no', label: 'Non' },
    ],
  },
  {
    name: 'hasBeenTerminated',
    type: 'select',
    required: true,
    label: 'Contrat résilié',
    subsection: {
      id: 'insurance_history',
      label: "Historique d'assurance",
    },
    options: [
      { value: 'no', label: 'Non' },
      { value: 'claim', label: 'Oui, pour sinistre' },
      { value: 'false_declaration', label: 'Oui, pour fausse déclaration' },
      { value: 'unpaid_premium', label: 'Oui, pour prime impayée' },
      { value: 'other', label: 'Oui, pour autre raison' },
    ],
  },
  {
    name: 'terminationReason',
    type: 'text',
    required: false,
    label: 'Raison de la résiliation',
    subsection: {
      id: 'insurance_history',
      label: "Historique d'assurance",
    },
    showWhen: { field: 'hasBeenTerminated', equals: 'other' },
    placeholder: 'Précisez la raison',
  },
  {
    name: 'claimsLast3Years',
    type: 'select',
    required: true,
    label: 'Sinistres des 3 dernières années',
    subsection: {
      id: 'claims_history',
      label: 'Historique des sinistres',
    },
    options: [
      { value: '0', label: 'Aucun' },
      { value: '1', label: '1' },
      { value: '2', label: '2' },
      { value: '3', label: '3' },
      { value: '4', label: '4' },
      { value: '5_plus', label: '5 ou plus' },
    ],
  },
  {
    name: 'hitAndRun',
    type: 'select',
    required: true,
    label: 'Délit de fuite',
    subsection: {
      id: 'claims_history',
      label: 'Historique des sinistres',
    },
    options: [
      { value: 'never', label: 'Jamais' },
      { value: 'less_5_years', label: 'Oui, dans les 5 dernières années' },
      { value: 'more_5_years', label: 'Oui, il y a plus de 5 années' },
    ],
  },
  {
    name: 'drugTestPositive',
    type: 'select',
    required: true,
    label: 'Test positif aux drogues',
    subsection: {
      id: 'claims_history',
      label: 'Historique des sinistres',
    },
    options: [
      { value: 'never', label: 'Jamais' },
      { value: 'less_5_years', label: 'Oui, dans les 5 dernières années' },
      { value: 'more_5_years', label: 'Oui, il y a plus de 5 années' },
    ],
  },
  {
    name: 'alcoholTestPositive',
    type: 'select',
    required: true,
    label: "Test positif à l'alcool",
    subsection: {
      id: 'claims_history',
      label: 'Historique des sinistres',
    },
    options: [
      { value: 'never', label: 'Jamais' },
      { value: 'less_5_years', label: 'Oui, dans les 5 dernières années' },
      { value: 'more_5_years', label: 'Oui, il y a plus de 5 années' },
    ],
  },

  // Votre contrat
  {
    name: 'previousInsurer',
    type: 'text',
    required: false,
    label: 'Ancien assureur',
    subsection: {
      id: 'contract_details',
      label: 'Détails du contrat',
    },
    placeholder: 'Rechercher un assureur...',
    helperText: 'Mon dernier assureur Auto',
  },
  {
    name: 'currentCoverageLevel',
    type: 'select',
    required: true,
    label: 'Niveau de couverture actuel',
    subsection: {
      id: 'contract_details',
      label: 'Détails du contrat',
    },
    helpText: 'Niveau de couverture de votre contrat actuel',
    example: 'Exemple: Si vous avez une assurance tous risques, choisissez "Assuré tous risques"',
    tooltip: 'Le niveau de couverture actuel influence les tarifs',
    options: [
      { value: 'not_insured', label: 'Non assuré' },
      { value: 'third_party', label: 'Assuré au tiers' },
      { value: 'comprehensive', label: 'Assuré tous risques' },
      { value: 'other', label: 'Autre' },
    ],
  },
  {
    name: 'contractOlderThanYear',
    type: 'select',
    required: false,
    label: "Contrat de plus d'un an",
    subsection: {
      id: 'contract_details',
      label: 'Détails du contrat',
    },
    showWhen: { field: 'isCurrentlyInsured', in: ['main_driver', 'secondary_driver'] },
    options: [
      { value: 'yes', label: 'Oui' },
      { value: 'no', label: 'Non' },
    ],
  },
  {
    name: 'contractExpiryMonth',
    type: 'select',
    required: false,
    label: "Mois d'expiration du contrat",
    subsection: {
      id: 'contract_details',
      label: 'Détails du contrat',
    },
    showWhen: { field: 'isCurrentlyInsured', in: ['main_driver', 'secondary_driver'] },
    options: [
      { value: 'january', label: 'Janvier' },
      { value: 'february', label: 'Février' },
      { value: 'march', label: 'Mars' },
      { value: 'april', label: 'Avril' },
      { value: 'may', label: 'Mai' },
      { value: 'june', label: 'Juin' },
      { value: 'july', label: 'Juillet' },
      { value: 'august', label: 'Août' },
      { value: 'september', label: 'Septembre' },
      { value: 'october', label: 'Octobre' },
      { value: 'november', label: 'Novembre' },
      { value: 'december', label: 'Décembre' },
    ],
  },
  {
    name: 'desiredCoverageLevel',
    type: 'select',
    required: true,
    label: 'Niveau de couverture souhaité',
    subsection: {
      id: 'contract_details',
      label: 'Détails du contrat',
    },
    helpText: 'Niveau de protection souhaité pour votre nouveau contrat',
    example: 'Exemple: Si vous voulez une couverture complète, choisissez "Tous risques"',
    tooltip: 'Plus la couverture est étendue, plus la prime est élevée',
    options: [
      { value: 'third_party_basic', label: 'Tiers simple (Responsabilité Civile)' },
      { value: 'third_party_glass', label: 'Tiers + bris de glace' },
      { value: 'third_party_glass_theft', label: 'Tiers + bris de glace + vol et incendie' },
      { value: 'comprehensive', label: 'Tous risques' },
    ],
  },
  // Additional missing fields for complete schema compliance
  {
    name: 'motorization',
    type: 'text',
    required: false,
    label: 'Motorisation',
    subsection: {
      id: 'vehicle_identification',
      label: 'Identification du véhicule',
    },
    placeholder: 'Ex: 1.6 BlueHDi 120',
    validation: { maxLength: 100 },
  },
  {
    name: 'previousVehicleRetention',
    type: 'select',
    required: false,
    label: 'Conservation du véhicule précédent',
    subsection: {
      id: 'vehicle_identification',
      label: 'Identification du véhicule',
    },
    options: [
      { value: '5_years_plus', label: 'Plus de 5 ans' },
      { value: 'less_1_year', label: 'Moins de 1 an' },
      { value: 'other', label: 'Autre' },
    ],
  },
  {
    name: 'workParkingCity',
    type: 'text',
    required: false,
    label: 'Ville de stationnement au travail',
    subsection: {
      id: 'vehicle_usage',
      label: 'Usage du véhicule',
    },
    showWhen: { field: 'usageType', in: ['private_work', 'private_professional'] },
    validation: { minLength: 2, maxLength: 100 },
    placeholder: 'Ville',
  },
  {
    name: 'hasAdditionalDrivers',
    type: 'checkbox',
    required: true,
    label: 'Conducteurs supplémentaires',
    subsection: {
      id: 'additional_drivers',
      label: 'Conducteurs supplémentaires',
    },
    helperText: 'Y a-t-il d\'autres conducteurs réguliers du véhicule ?',
  },
  {
    name: 'additionalDriverAge',
    type: 'number',
    required: false,
    label: 'Âge du conducteur supplémentaire',
    subsection: {
      id: 'additional_drivers',
      label: 'Conducteurs supplémentaires',
    },
    showWhen: { field: 'hasAdditionalDrivers', equals: true },
    validation: { min: 16, max: 99 },
  },
  {
    name: 'additionalDriverLicenseDate',
    type: 'date',
    required: false,
    label: 'Date d\'obtention du permis (conducteur supplémentaire)',
    subsection: {
      id: 'additional_drivers',
      label: 'Conducteurs supplémentaires',
    },
    showWhen: { field: 'hasAdditionalDrivers', equals: true },
    mask: {
      pattern: '99/99/9999',
      placeholder: 'JJ/MM/AAAA',
      guide: true,
    },
  },
  {
    name: 'additionalDriverHistory',
    type: 'textarea',
    required: false,
    label: 'Historique du conducteur supplémentaire',
    subsection: {
      id: 'additional_drivers',
      label: 'Conducteurs supplémentaires',
    },
    showWhen: { field: 'hasAdditionalDrivers', equals: true },
    validation: { maxLength: 200 },
    placeholder: 'Décrivez l\'historique du conducteur (sinistres, suspension, etc.)',
  },
  {
    name: 'additionalDriverUsage',
    type: 'textarea',
    required: false,
    label: 'Usage par le conducteur supplémentaire',
    subsection: {
      id: 'additional_drivers',
      label: 'Conducteurs supplémentaires',
    },
    showWhen: { field: 'hasAdditionalDrivers', equals: true },
    validation: { maxLength: 200 },
    placeholder: 'Décrivez l\'usage du véhicule par ce conducteur',
  },
];
