import type { RawFormFieldDefinition } from '../../types/comparison.types';

// Home-specific fields
export const homeSpecificFields: RawFormFieldDefinition[] = [
  // Votre logement
  {
    name: 'residenceType',
    type: 'select',
    required: true,
    subsection: {
      id: 'property_details',
      label: 'Détails du logement',
    },
    helpText: 'Type de logement à assurer',
    example: 'Exemple: Si vous habitez dans une maison, choisissez "Maison"',
    tooltip: "Le type de logement influence le coût de l'assurance",
    options: [
      { value: 'house', label: 'Maison' },
      { value: 'apartment', label: 'Appartement' },
      { value: 'studio', label: 'Studio' },
      { value: 'duplex', label: 'Duplex' },
      { value: 'loft', label: 'Loft' },
    ],
  },
  {
    name: 'residenceStatus',
    type: 'select',
    required: true,
    subsection: {
      id: 'property_details',
      label: 'Détails du logement',
    },
    helpText: "Statut d'occupation du logement",
    example: 'Exemple: Si vous êtes propriétaire, choisissez "Propriétaire"',
    tooltip: "Le statut d'occupation peut influencer les garanties disponibles",
    options: [
      { value: 'owner', label: 'Propriétaire' },
      { value: 'tenant', label: 'Locataire' },
      { value: 'co_owner', label: 'Copropriétaire' },
      { value: 'free_occupant', label: 'Occupant à titre gratuit' },
    ],
  },
  {
    name: 'propertyAddress',
    type: 'text',
    required: true,
    subsection: {
      id: 'property_details',
      label: 'Détails du logement',
    },
    helpText: 'Adresse complète du logement à assurer',
    example: 'Exemple: 123 rue de la Paix, 75001 Paris',
    tooltip: "L'adresse est utilisée pour évaluer les risques locaux",
    validation: { minLength: 10, maxLength: 200 },
    placeholder: 'Adresse du logement',
  },
  {
    name: 'propertyPostalCode',
    type: 'text',
    required: true,
    validation: { pattern: '^[0-9]{5}$' },
    placeholder: 'Code postal',
  },
  {
    name: 'propertyCity',
    type: 'text',
    required: true,
    validation: { minLength: 2, maxLength: 100 },
    placeholder: 'Ville',
  },
  {
    name: 'constructionYear',
    type: 'date',
    required: true,
    subsection: {
      id: 'property_details',
      label: 'Détails du logement',
    },
    helpText: 'Année de construction du logement',
    example: 'Exemple: Si votre maison a été construite en 1985, entrez 1985',
    tooltip: "L'âge du logement influence le risque et la prime",
    mask: {
      pattern: '9999',
      placeholder: 'AAAA',
      guide: true,
    },
  },
  {
    name: 'livingArea',
    type: 'number',
    required: true,
    subsection: {
      id: 'property_details',
      label: 'Détails du logement',
    },
    helpText: 'Surface habitable en m²',
    example: 'Exemple: Si votre logement fait 85 m², entrez 85',
    tooltip: 'La surface influence le coût de reconstruction en cas de sinistre',
    validation: { min: 10, max: 2000 },
    helperText: 'Surface habitable (m²)',
  },
  {
    name: 'numberOfRooms',
    type: 'number',
    required: true,
    subsection: {
      id: 'property_details',
      label: 'Détails du logement',
    },
    helpText: 'Nombre de pièces principales',
    example: 'Exemple: Si vous avez 4 pièces, entrez 4',
    tooltip: 'Le nombre de pièces aide à évaluer la valeur du contenu',
    validation: { min: 1, max: 20 },
    helperText: 'Nombre de pièces',
  },
  {
    name: 'floorNumber',
    type: 'number',
    required: false,
    showWhen: { field: 'residenceType', in: ['apartment', 'duplex', 'loft'] },
    subsection: {
      id: 'property_details',
      label: 'Détails du logement',
    },
    helpText: "Numéro d'étage (pour les logements collectifs)",
    example: 'Exemple: Si vous êtes au 3ème étage, entrez 3',
    tooltip: "L'étage peut influencer le risque d'intrusion et d'inondation",
    validation: { min: 0, max: 50 },
    helperText: "Numéro d'étage",
  },
  {
    name: 'hasElevator',
    type: 'select',
    required: false,
    showWhen: { field: 'residenceType', in: ['apartment', 'duplex'] },
    subsection: {
      id: 'property_details',
      label: 'Détails du logement',
    },
    helpText: "Présence d'un ascenseur dans l'immeuble",
    example: 'Exemple: Si votre immeuble a un ascenseur, choisissez "Oui"',
    tooltip: "L'ascenseur peut influencer les garanties de responsabilité civile",
    options: [
      { value: 'yes', label: 'Oui' },
      { value: 'no', label: 'Non' },
    ],
  },
  {
    name: 'propertyValue',
    type: 'number',
    required: true,
    subsection: {
      id: 'property_details',
      label: 'Détails du logement',
    },
    helpText: 'Valeur estimée du logement',
    example: 'Exemple: Si votre logement vaut 250 000 €, entrez 250000',
    tooltip: 'Cette valeur est utilisée pour calculer les garanties',
    validation: { min: 10000, max: 5000000 },
    helperText: 'Valeur du logement (€)',
  },

  // Votre profil
  {
    name: 'gender',
    type: 'select',
    required: true,
    subsection: {
      id: 'policyholder_profile',
      label: "Profil de l'assuré",
    },
    helpText: 'Votre genre',
    example: 'Exemple: Si vous êtes un homme, choisissez "Un homme"',
    tooltip: 'Le genre influence les statistiques de risque',
    options: [
      { value: 'male', label: 'Un homme' },
      { value: 'female', label: 'Une femme' },
    ],
  },
  {
    name: 'birthDate',
    type: 'date',
    required: true,
    subsection: {
      id: 'policyholder_profile',
      label: "Profil de l'assuré",
    },
    helpText: 'Votre date de naissance',
    example: 'Exemple: Si vous êtes né le 15/03/1990, entrez 15/03/1990',
    tooltip: "L'âge influence le coût de l'assurance",
    mask: {
      pattern: '99/99/9999',
      placeholder: 'JJ/MM/AAAA',
      guide: true,
    },
  },
  {
    name: 'maritalStatus',
    type: 'select',
    required: true,
    subsection: {
      id: 'policyholder_profile',
      label: "Profil de l'assuré",
    },
    helpText: 'Votre situation matrimoniale',
    example: 'Exemple: Si vous êtes marié, choisissez "Marié(e)"',
    tooltip: 'La situation familiale peut influencer les tarifs',
    options: [
      { value: 'single', label: 'Célibataire' },
      { value: 'married', label: 'Marié(e)' },
      { value: 'cohabiting', label: 'En concubinage' },
      { value: 'pacs', label: 'Pacsé(e)' },
    ],
  },
  {
    name: 'profession',
    type: 'select',
    required: true,
    subsection: {
      id: 'policyholder_profile',
      label: "Profil de l'assuré",
    },
    helpText: 'Votre profession actuelle',
    example: 'Exemple: Si vous êtes salarié cadre, choisissez "Salarié(e) cadre du secteur privé"',
    tooltip: 'La profession influence le profil de risque',
    options: [
      { value: 'student', label: 'Étudiant' },
      { value: 'private_executive', label: 'Salarié(e) cadre du secteur privé' },
      { value: 'private_employee', label: 'Salarié(e) non-cadre du secteur privé' },
      { value: 'public_executive', label: 'Salarié(e) cadre du secteur public' },
      { value: 'public_employee', label: 'Salarié(e) non-cadre du secteur public' },
      { value: 'independent', label: 'Indépendant(e)' },
      { value: 'entrepreneur', label: 'Entrepreneur(e)' },
      { value: 'retired', label: 'Retraité' },
      { value: 'unemployed', label: 'Sans emploi' },
    ],
  },
  {
    name: 'numberOfChildren',
    type: 'select',
    required: true,
    subsection: {
      id: 'policyholder_profile',
      label: "Profil de l'assuré",
    },
    helpText: "Nombre d'enfants à votre charge",
    example: 'Exemple: Si vous avez 2 enfants, choisissez "2"',
    tooltip: "Le nombre d'enfants peut influencer certaines garanties",
    options: [
      { value: '0', label: '0' },
      { value: '1', label: '1' },
      { value: '2', label: '2' },
      { value: '3_plus', label: '3 ou plus' },
    ],
  },
  {
    name: 'childrenBirthYears',
    type: 'object',
    required: false,
    showWhen: { field: 'numberOfChildren', in: ['1', '2', '3_plus'] },
    subsection: {
      id: 'policyholder_profile',
      label: "Profil de l'assuré",
    },
    helpText: 'Année de naissance des enfants',
    example: 'Exemple: Si votre enfant est né en 2010, entrez 2010',
    tooltip: "L'âge des enfants peut influencer certaines garanties",
    objectSchema: {
      type: 'array',
      itemSchema: {
        type: 'object',
        fields: [
          {
            name: 'year',
            type: 'number',
            required: true,
            validation: { min: 1990, max: 2025 },
          },
        ],
      },
    },
  },
  {
    name: 'residenceType',
    type: 'select',
    required: true,
    subsection: {
      id: 'policyholder_profile',
      label: "Profil de l'assuré",
    },
    helpText: 'Type de résidence principale',
    example: 'Exemple: Si vous habitez dans une maison, choisissez "Une maison"',
    tooltip: "Le type de résidence influence le risque d'assurance",
    options: [
      { value: 'house', label: 'Une maison' },
      { value: 'apartment', label: 'Un appartement' },
    ],
  },
  {
    name: 'residenceStatus',
    type: 'select',
    required: true,
    subsection: {
      id: 'policyholder_profile',
      label: "Profil de l'assuré",
    },
    helpText: "Statut d'occupation de votre résidence",
    example: 'Exemple: Si vous êtes locataire, choisissez "Locataire ou colocataire"',
    tooltip: "Le statut d'occupation peut influencer les garanties",
    options: [
      { value: 'tenant', label: 'Locataire ou colocataire' },
      { value: 'owner', label: 'Propriétaire' },
      { value: 'other', label: 'Autre' },
    ],
  },
  {
    name: 'residenceStability',
    type: 'select',
    required: true,
    subsection: {
      id: 'policyholder_profile',
      label: "Profil de l'assuré",
    },
    helpText: 'Stabilité de votre résidence',
    example: 'Exemple: Si vous habitez toujours au même endroit, choisissez "À une adresse fixe"',
    tooltip: 'La stabilité résidentielle peut influencer les tarifs',
    options: [
      { value: 'fixed', label: 'À une adresse fixe' },
      { value: 'various', label: 'À diverses adresses' },
    ],
  },

  // Vos antécédents
  {
    name: 'isCurrentlyInsured',
    type: 'select',
    required: true,
    subsection: {
      id: 'insurance_history',
      label: "Historique d'assurance",
    },
    helpText: 'Êtes-vous actuellement assuré en habitation ?',
    example: 'Exemple: Si vous avez déjà une assurance habitation, choisissez "Oui"',
    tooltip: "Un historique d'assurance peut vous faire bénéficier de tarifs préférentiels",
    options: [
      { value: 'yes', label: 'Oui' },
      { value: 'no', label: 'Non' },
    ],
  },
  {
    name: 'yearsInsured',
    type: 'select',
    required: true,
    showWhen: { field: 'isCurrentlyInsured', equals: 'yes' },
    subsection: {
      id: 'insurance_history',
      label: "Historique d'assurance",
    },
    helpText: "Depuis combien d'années êtes-vous assuré ?",
    example: 'Exemple: Si vous êtes assuré depuis 5 ans, choisissez "5 ans"',
    tooltip: 'Plus vous êtes assuré longtemps, plus vous pouvez bénéficier de réductions',
    helperText: "Sélectionnez depuis combien d'années vous êtes assuré",
    options: [], // Will be populated dynamically by frontend using dayjs
  },
  {
    name: 'previousInsurer',
    type: 'autocomplete',
    required: false,
    showWhen: { field: 'isCurrentlyInsured', equals: 'yes' },
    subsection: {
      id: 'insurance_history',
      label: "Historique d'assurance",
    },
    helpText: 'Votre assureur habitation actuel',
    example: 'Exemple: Tapez "Maif" pour trouver votre assureur',
    tooltip: 'Cela nous aide à évaluer votre profil de risque',
    placeholder: 'Rechercher un assureur...',
    autocomplete: {
      endpoint: 'api/v1/insurers/search',
      minLength: 2,
      debounceMs: 300,
    },
  },
  {
    name: 'hasBeenTerminated',
    type: 'select',
    required: true,
    subsection: {
      id: 'insurance_history',
      label: "Historique d'assurance",
    },
    helpText: 'Votre contrat a-t-il déjà été résilié ?',
    example: 'Exemple: Si votre contrat a été résilié pour sinistre, choisissez "Oui, pour sinistre"',
    tooltip: 'Les résiliations antérieures peuvent influencer les tarifs',
    options: [
      { value: 'no', label: 'Non' },
      { value: 'claim', label: 'Oui, pour sinistre' },
      { value: 'false_declaration', label: 'Oui, pour fausse déclaration' },
      { value: 'unpaid_premium', label: 'Oui, pour prime impayée' },
      { value: 'other', label: 'Oui, pour autre raison' },
    ],
  },
  {
    name: 'terminationReason',
    type: 'text',
    required: false,
    showWhen: { field: 'hasBeenTerminated', equals: 'other' },
    subsection: {
      id: 'insurance_history',
      label: "Historique d'assurance",
    },
    helpText: 'Précisez la raison de la résiliation',
    example: 'Exemple: "Déménagement à l\'étranger"',
    tooltip: 'Cette information nous aide à mieux comprendre votre situation',
    placeholder: 'Précisez la raison',
  },
  {
    name: 'claimsLast5Years',
    type: 'select',
    required: true,
    subsection: {
      id: 'insurance_history',
      label: "Historique d'assurance",
    },
    helpText: 'Nombre de sinistres déclarés dans les 5 dernières années',
    example: 'Exemple: Si vous avez eu 1 sinistre, choisissez "1"',
    tooltip: "Le nombre de sinistres influence directement le coût de l'assurance",
    options: [
      { value: '0', label: 'Aucun' },
      { value: '1', label: '1' },
      { value: '2', label: '2' },
      { value: '3', label: '3' },
      { value: '4', label: '4' },
      { value: '5_plus', label: '5 ou plus' },
    ],
  },

  // Votre contrat
  {
    name: 'contractStartDate',
    type: 'date',
    required: true,
    subsection: {
      id: 'contract_details',
      label: 'Détails du contrat',
    },
    helpText: 'Date souhaitée du début du contrat',
    example: 'Exemple: Si vous voulez commencer le 01/01/2024, entrez 01/01/2024',
    tooltip: 'La date de début détermine quand vos garanties prennent effet',
    mask: {
      pattern: '99/99/9999',
      placeholder: 'JJ/MM/AAAA',
      guide: true,
    },
    shortcuts: [
      { value: 'asap', label: 'Dès que possible', description: 'Début immédiat du contrat' },
      { value: 'tomorrow', label: 'Demain', description: 'Début demain' },
      { value: 'next_month', label: 'Mois prochain', description: 'Début le 1er du mois prochain' },
    ],
  },
  {
    name: 'desiredCoverageLevel',
    type: 'card',
    required: true,
    subsection: {
      id: 'contract_details',
      label: 'Détails du contrat',
    },
    helpText: 'Niveau de protection souhaité pour votre logement',
    example: 'Exemple: Si vous voulez une couverture complète, choisissez "Premium"',
    tooltip: 'Plus la couverture est étendue, plus la prime est élevée',
    options: [
      { value: 'basic', label: 'Basique', icon: 'MdHome', description: 'Couverture de base' },
      { value: 'extended', label: 'Étendue', icon: 'MdHomeWork', description: 'Couverture étendue' },
      { value: 'premium', label: 'Premium', icon: 'MdCastle', description: 'Couverture premium complète' },
    ],
  },
  {
    name: 'deductiblePreference',
    type: 'radio',
    required: true,
    subsection: {
      id: 'contract_details',
      label: 'Détails du contrat',
    },
    helpText: 'Montant de franchise souhaité',
    example: 'Exemple: Si vous préférez payer moins cher chaque mois, choisissez "Élevée"',
    tooltip: 'Une franchise élevée réduit la prime mais augmente votre participation en cas de sinistre',
    options: [
      { value: 'low', label: 'Faible (150€)' },
      { value: 'medium', label: 'Moyenne (300€)' },
      { value: 'high', label: 'Élevée (500€)' },
    ],
  },
  {
    name: 'paymentFrequency',
    type: 'radio',
    required: true,
    subsection: {
      id: 'contract_details',
      label: 'Détails du contrat',
    },
    helpText: 'Fréquence de paiement souhaitée',
    example: 'Exemple: Si vous préférez payer chaque mois, choisissez "Mensuel"',
    tooltip: 'Le paiement annuel peut vous faire bénéficier de réductions',
    options: [
      { value: 'monthly', label: 'Mensuel' },
      { value: 'annual', label: 'Annuel' },
    ],
  },
  {
    name: 'maxAnnualPremium',
    type: 'number',
    required: true,
    showWhen: { field: 'paymentFrequency', equals: 'annual' },
    subsection: {
      id: 'contract_details',
      label: 'Détails du contrat',
    },
    helpText: "Budget maximum annuel pour l'assurance",
    example: 'Exemple: Si votre budget maximum est de 500€ par an, entrez 500',
    tooltip: 'Cela nous aide à vous proposer des offres dans votre budget',
    validation: { min: 100, max: 3000 },
    helperText: 'Budget maximum annuel (€)',
  },
  {
    name: 'maxMonthlyPremium',
    type: 'number',
    required: true,
    showWhen: { field: 'paymentFrequency', equals: 'monthly' },
    subsection: {
      id: 'contract_details',
      label: 'Détails du contrat',
    },
    helpText: "Budget maximum mensuel pour l'assurance",
    example: 'Exemple: Si votre budget maximum est de 50€ par mois, entrez 50',
    tooltip: 'Cela nous aide à vous proposer des offres dans votre budget',
    validation: { min: 10, max: 300 },
    helperText: 'Budget maximum mensuel (€)',
  },

  // Vos coordonnées
  {
    name: 'civility',
    type: 'select',
    required: true,
    subsection: {
      id: 'personal_contact',
      label: 'Coordonnées personnelles',
    },
    helpText: 'Votre civilité',
    example: 'Exemple: Si vous êtes un homme, choisissez "M."',
    tooltip: 'La civilité est utilisée pour personnaliser votre devis',
    options: [
      { value: 'M.', label: 'M.' },
      { value: 'Mme', label: 'Mme' },
    ],
  },
  {
    name: 'firstName',
    type: 'text',
    required: true,
    subsection: {
      id: 'personal_contact',
      label: 'Coordonnées personnelles',
    },
    helpText: 'Votre prénom',
    example: 'Exemple: Si votre prénom est Jean, entrez "Jean"',
    tooltip: 'Votre prénom sera utilisé pour personnaliser votre devis',
    validation: { minLength: 2, maxLength: 50 },
    placeholder: 'Prénom',
  },
  {
    name: 'lastName',
    type: 'text',
    required: true,
    subsection: {
      id: 'personal_contact',
      label: 'Coordonnées personnelles',
    },
    helpText: 'Votre nom de famille',
    example: 'Exemple: Si votre nom est Dupont, entrez "Dupont"',
    tooltip: 'Votre nom sera utilisé pour personnaliser votre devis',
    validation: { minLength: 2, maxLength: 50 },
    placeholder: 'Nom',
  },
  {
    name: 'address',
    type: 'text',
    required: true,
    subsection: {
      id: 'personal_contact',
      label: 'Coordonnées personnelles',
    },
    helpText: 'Votre adresse de résidence',
    example: 'Exemple: 123 rue de la Paix, 75001 Paris',
    tooltip: 'Votre adresse est utilisée pour évaluer les risques locaux',
    validation: { minLength: 10, maxLength: 200 },
    placeholder: 'Adresse',
  },
  {
    name: 'postalCode',
    type: 'text',
    required: true,
    subsection: {
      id: 'personal_contact',
      label: 'Coordonnées personnelles',
    },
    helpText: 'Code postal de votre adresse',
    example: 'Exemple: Si vous habitez à Paris 1er, entrez "75001"',
    tooltip: "Le code postal influence l'évaluation des risques locaux",
    validation: { pattern: '^[0-9]{5}$' },
    placeholder: 'Code postal',
  },
  {
    name: 'city',
    type: 'text',
    required: true,
    subsection: {
      id: 'personal_contact',
      label: 'Coordonnées personnelles',
    },
    helpText: 'Ville de résidence',
    example: 'Exemple: Si vous habitez à Paris, entrez "Paris"',
    tooltip: "La ville est utilisée pour l'évaluation des risques",
    validation: { minLength: 2, maxLength: 100 },
    placeholder: 'Ville',
  },
  {
    name: 'email',
    type: 'text',
    required: true,
    subsection: {
      id: 'personal_contact',
      label: 'Coordonnées personnelles',
    },
    helpText: 'Votre adresse email pour recevoir votre devis',
    example: 'Exemple: jean.dupont@email.com',
    tooltip: 'Nous vous enverrons votre devis par email',
    validation: { pattern: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$' },
    placeholder: 'Email',
  },
  {
    name: 'phone',
    type: 'text',
    required: true,
    subsection: {
      id: 'personal_contact',
      label: 'Coordonnées personnelles',
    },
    helpText: 'Votre numéro de téléphone',
    example: 'Exemple: 01 23 45 67 89',
    tooltip: 'Votre téléphone peut être utilisé pour vous contacter',
    validation: { pattern: '^[0-9]{10}$' },
    placeholder: 'Téléphone',
    mask: {
      pattern: '99 99 99 99 99',
      placeholder: '01 23 45 67 89',
      guide: true,
    },
  },
];
